---
title: "oefendata_SFBN"
author: "afra"
date: "22 mei 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
setwd('~/R')
list.files()
```

```{r}
#read data into R
SFBN <- read.csv('raw_stage_data2.txt', header = FALSE, sep='\t')
```

```{r}
#remove rijen met NA
SFBN_y100 <- SFBN[rowSums(is.na(SFBN)) != ncol(SFBN), ]
```

```{r}
#gedeeld door 10, om naar stages te gaan
SFBN_stages <- cbind(SFBN_y100[, 1], floor(SFBN_y100[, 2:ncol(SFBN_y100)] / 10))
```

```{r}
# Add covariates, maak een covariate voor stadium 2a, 2b, 2c of 2d

# make a covariate matrix with one column
cov_matrix <- matrix (NA, nrow = nrow(SFBN_y100), ncol= 2)
colnames(cov_matrix) <- c('id', 'covariate')

#loop trough matrix looking for 21, 22, 23 or 24, add this value to the cov_matrix
for (rownumber in 1:nrow(SFBN_y100)) {
  for(colnumber in 1:ncol(SFBN_y100)) {
    covariate <- SFBN_y100[rownumber, colnumber]
    id <- SFBN_y100[rownumber, 1]
    
    cov_matrix[rownumber, 'id'] <- id
    if (is.na(covariate) | (covariate > 20) & (covariate < 25)) {
      cov_matrix[rownumber, 'covariate']  <- covariate
      break
    } 
  }
}
```

```{r}
SFBN_stages_long <- matrix(NA, nrow = 0, ncol=9)
colnames(SFBN_stages_long) <- c('id', 'from', 'to', 'trans', 'Tstart', 'Tstop', 'time', 'status', 'covariate')

max_time <- 60
ignore_stages <- c(1)

for (current_row in 1:nrow(SFBN_stages)) {
  current_time <- 0
  current_stage <- NA

  # start at col 2, col 1 is the ID
  for (current_col in 2:ncol(SFBN_stages)) {
    next_stage <- SFBN_stages[current_row, current_col]

    # skip columns without values or that are ignored
    if (is.na(next_stage) || next_stage %in% ignore_stages) {
      next()
    }

    if (is.na(current_stage)) {
      current_stage <- next_stage

      # matrix of single stage
      stage_long <- matrix(NA, nrow = 1, ncol = 9)
      colnames(stage_long) <- c('id', 'from', 'to', 'trans', 'Tstart', 'Tstop', 'time', 'status', 'covariate')

      stage_long[1, 'id'] <- SFBN_stages[current_row, 1]
      stage_long[1, 'from'] <- current_stage
      stage_long[1, 'Tstart'] <- current_time
      stage_long[1, 'Tstop'] <- current_time
      stage_long[1, 'time'] <- 0
      stage_long[1, 'status'] <- 1
    }

    if (current_stage != next_stage) {

      stage_long[1, 'to'] <- next_stage
      current_stage <- next_stage

      SFBN_stages_long <- rbind(SFBN_stages_long, stage_long)

      # matrix of single stage
      stage_long <- matrix(NA, nrow = 1, ncol=9)
      colnames(stage_long) <- c('id', 'from', 'to', 'trans', 'Tstart', 'Tstop', 'time', 'status', 'covariate')

      stage_long[1, 'id'] <- SFBN_stages[current_row, 1]
      stage_long[1, 'from'] <- current_stage
      stage_long[1, 'Tstart'] <- current_time
      stage_long[1, 'Tstop'] <- current_time
      stage_long[1, 'time'] <- 0
      stage_long[1, 'status'] <- 1

    }

    current_time <- current_time + 1
    stage_long[1, 'Tstop'] <- stage_long[1, 'Tstop'] + 1
    stage_long[1, 'time'] <- stage_long[1, 'time'] + 1

    if (current_time == max_time) {
      break;
    }
  }

  stage_long[1, 'to'] <- 0
  SFBN_stages_long <- rbind(SFBN_stages_long, stage_long)
}

```

```{r}
#add covariate to long matrix
for(y in 1:nrow(SFBN_stages_long)) {
long_id <- SFBN_stages_long[y,'id']

for(z in 1:nrow(cov_matrix)) {
  if (cov_matrix[z, 'id'] == long_id) {
    cov <- cov_matrix [z , 'covariate']
    
    SFBN_stages_long[y, 'covariate'] <- cov
    }
  }
}

```

```{r}
# Transitie: trans variabele
for (i in 1:nrow(SFBN_stages_long)) {
  from <- SFBN_stages_long[i, 'from']
  to <- SFBN_stages_long[i, 'to']
  
  
  if ((from == 2) & (to == 3)) {
    SFBN_stages_long[i, 'trans'] <- 1
  } 
  else if ((from == 2) & (to == 4)) {
    SFBN_stages_long[i, 'trans'] <- 2  
  }
  else if ((from == 2) & (to == 0)) {
    SFBN_stages_long[i, 'trans'] <- 3  
  }
  else if ((from == 3) & (to == 4)) {
    SFBN_stages_long[i, 'trans'] <- 4  
  }
  else if ((from == 3) & (to == 0)) {
    SFBN_stages_long[i, 'trans'] <- 5  
  }
  else if ((from == 4) & (to == 3)) {
    SFBN_stages_long[i, 'trans'] <- 6  
  }
  else if ((from == 4) & (to == 0)) {
    SFBN_stages_long[i, 'trans'] <- 7  
  }
}

```

```{r}
tmat <- transMat(x = list(c(2, 3, 4), c(3, 4), c(2, 4), c()), names = c(2, 3, 4, 0))
```

```{r}
SFBN_final <- msprep(data = SFBN_stages_long, trans = tmat, time = c(NA, "rec", "ae", + "recae", "rel", "srv"), status = c(NA, "rec.s", "ae.s", "recae.s", + "rel.s", "srv.s"), keep = c("match", "proph", "year", "agecl"))
```










```{r}
#library(mstate)
events(SFBN_stages_long)

```






















```{r}
# example markov model
# MODEL 1 Markov model with stratifi ed hazards
c1 <-coxph(Surv(Tstart, Tstop, status) ~ dissub1.1 +
dissub2.1 +age1.1 + age2.1 + drmatch.1 + tcd.1 +
dissub1.2 + dissub2.2 + age1.2 + age2.2 + drmatch.2 +
tcd.2 + dissub1.3 + dissub2.3 + age1.3 + age2.3 +
drmatch.3 + tcd.3 + strata(trans), data=msbmt,
method="breslow")
```

