---
title: "SFBN_wide_format"
author: "afra"
date: "11 juni 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# niet nodig
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
setwd('~/R_files')
list.files()
```

```{r}
install.packages("mstate")
library(mstate)

install.packages("survival")
library(survival)
```

```{r}
# read data into R. 
# 11 is stage 1a, 12 is stage 1b, etc
SFBN <- read.csv('raw_stage_data2.txt', header = FALSE, sep='\t')
```

```{r}
# remove rows with NA
SFBN_y100 <- SFBN[rowSums(is.na(SFBN)) != ncol(SFBN), ]
```

```{r}
# divide by 10, in order to have stages 1 - 4
SFBN_stages <- cbind(SFBN_y100[, 1], floor(SFBN_y100[, 2:ncol(SFBN_y100)] / 10))
```

```{r}
# Make wide matrix with stages 1, 2, 3.1, 4, 3.2 and status. Add a covariate named startstage, which shows whether the patient started in stage 2a, 2b, 2c or 2d 

SFBN_wide <- matrix(NA, nrow = nrow(SFBN_stages), ncol = 10)
colnames(SFBN_wide) <- c("ID", "stage2", "stage2.s", "stage31", "stage31.s", "stage4", "stage4.s", "stage32", "stage32.s", "startstage")

for(current_row in 1:nrow(SFBN_stages)) {
  prev_stage <- 0
  SFBN_wide[current_row, "ID"] <- SFBN_stages[current_row, 1]
  for(current_col in 2:ncol(SFBN_stages)) {
    cur_stage <- SFBN_stages[current_row, current_col]
    
    if(is.na(cur_stage)){
      break
    }
    
    if (prev_stage == cur_stage){
      next()
    }
    
    if (cur_stage == 2) {
      SFBN_wide[current_row, "stage2"] <- current_col
      SFBN_wide[current_row, "stage2.s"] <- 1
      SFBN_wide[current_row, "startstage"] <- SFBN_y100[current_row, current_col]
    }
    if (cur_stage == 3) {
      if (prev_stage < 3) {
        SFBN_wide[current_row, "stage31"] <- current_col
        SFBN_wide[current_row, "stage31.s"] <- 1
      }
      if (prev_stage > 3) {
        SFBN_wide[current_row, "stage32"] <- current_col
        SFBN_wide[current_row, "stage32.s"] <- 1
      }
    }
    if (cur_stage == 4) {
      SFBN_wide[current_row, "stage4"] <- current_col
      SFBN_wide[current_row, "stage4.s"] <- 1
    }
    prev_stage <- cur_stage
  }
  
  if (is.na(SFBN_wide[current_row, "stage2"])) {
    SFBN_wide[current_row, "stage2"] <- current_col
    SFBN_wide[current_row, "stage2.s"] <- 0
  }
  if (is.na(SFBN_wide[current_row, "stage31"])) {
    SFBN_wide[current_row, "stage31"] <- current_col
    SFBN_wide[current_row, "stage31.s"] <- 0
  }
  if (is.na(SFBN_wide[current_row, "stage4"])) {
    SFBN_wide[current_row, "stage4"] <- current_col
    SFBN_wide[current_row, "stage4.s"] <- 0
  }
  if (is.na(SFBN_wide[current_row, "stage32"])) {
    SFBN_wide[current_row, "stage32"] <- current_col
    SFBN_wide[current_row, "stage32.s"] <- 0
    
  }
}
```

```{r}
# added: re-assign variable names so msprep recognises them
names(SFBN_wide) <- c("id", "stage2", "stage2.s", "stage31", "stage31.s", "stage4", "stage4.s", "stage32", "stage32.s", "startstage")

```

```{r}
# Make transition matrix
tmat <- transMat(x = list(c(2, 3), c(3), c(4), c()), names = c("stage2", "stage31", "stage4", "stage32"))
```

```{r}
# look at paths
paths(tmat)
```

```{r}
# Change data from wide into long format 
# Hier gaat het fout, ID en startstage kloppen niet

covs <- "startstage"

sfbnlong <- msprep(time = c( "stage2", "stage31", "stage4", "stage32"), status = c(  "stage2.s", "stage31.s", "stage4.s", "stage32.s"), id = "id", data = SFBN_wide, trans = tmat, keep = covs) 
```

```{r}
events(sfbnlong)
```
```{r}
# add the covariates
expcovs <-expand.covs(sfbnlong, covs = covs, append = FALSE, longnames = FALSE)
head(expcovs)
```


```{r}
# Markov model with stratified hazards
# onze data is Markov want risk hangt niet af van voorgaand risk

c1 <-coxph(Surv(Tstart, Tstop, status) ~ (startstage + strata(trans)), data=sfbnlong,
method="breslow")

summary(c1)
```
```{r}
#use msfit function to plot the estimated cumulative transition intensities in the multi-state model
# msfit(object, newdata, variance=TRUE, vartype=c("aalen","greenwood"), trans)

# new data, to check whether results are the same for transition 1 as
# those in appendix E.1 of Therneau & Grambsch (2000)

newdata <- data.frame(trans=1:3,x1.1=c(0,0,0),x2.2=c(0,1,0),strata=1:3)
msfit(c1,newdata,trans=tmat)
```

